name: backend
type: proc
proc:
  build: bun install --cwd backend
  start: bun run --cwd backend start
  port: 4000
env:
  NS_MARIADB_HOSTNAME: ${NS_MARIADB_HOSTNAME}
  NS_MARIADB_USER: ${NS_MARIADB_USER}
  NS_MARIADB_PASSWORD: ${NS_MARIADB_PASSWORD}
  NS_MARIADB_DATABASE: ${NS_MARIADB_DATABASE}
  NS_MARIADB_PORT: ${NS_MARIADB_PORT}
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
